# MENENTUKAN IMAGE DASAR
FROM node:18.16

# PERINTAH YANG DIJALANKAN SAAT CREATE IMAGE
RUN apt update -y && npm install

# COPY SOURCE KE IMAGE
ADD . /app

# MAINTAINER IMAGE
LABEL email="mat0441@gmail.com"

# PERINTAH YANG DIJALANKAN PADA SAAT CONTAINER SUDAH UP
CMD ["npm", "start"]

# DESCRIBE EXPOSE PORT, JUST DESCRIBE
EXPOSE 3000